CREATE DATABASE pokeverso;
USE pokeverso;

CREATE USER 'usr_pokeverso'@'localhost' IDENTIFIED BY 'Po158575';
GRANT ALL PRIVILEGES ON pokeverso.* TO 'usr_pokeverso'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE geracoes (
	id_geracao INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    lancamento DATE NOT NULL,
    qtd_pokemon INT NOT NULL
);

CREATE TABLE jogos (
	id_jogo INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    lancamento DATE NOT NULL,
    id_geracao INT NOT NULL,
    CONSTRAINT chFkGeracaoJogo FOREIGN KEY (id_geracao) REFERENCES geracoes(id_geracao)
);

CREATE TABLE pokemon (
	id_pokemon INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    tipagem_1 VARCHAR(45) NOT NULL,
    tipagem_2 VARCHAR(45),
    foto_url VARCHAR(255) NOT NULL,
    cor_principal CHAR(7) NOT NULL,
    cor_secundaria CHAR(7) NOT NULL,
    id_geracao INT,
    CONSTRAINT chFkGeracaoPokemon FOREIGN KEY (id_geracao) REFERENCES geracoes(id_geracao)
);

CREATE TABLE usuario (
	id_usuario INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    admin TINYINT DEFAULT 0 NOT NULL,
    id_pokemon_favorito INT,
    id_jogo_favorito INT,
    id_geracao_favorita INT,
    CONSTRAINT chCKAdmin CHECK (admin IN (0, 1)),
	CONSTRAINT chFkPokemonFavorito FOREIGN KEY (id_pokemon_favorito) REFERENCES pokemon(id_pokemon),
    CONSTRAINT chFkJogoFavorito FOREIGN KEY (id_jogo_favorito) REFERENCES jogos(id_jogo),
    CONSTRAINT chFkGeracaoFavorita FOREIGN KEY (id_geracao_favorita) REFERENCES geracoes(id_geracao)
);

INSERT INTO geracoes (nome, lancamento, qtd_pokemon) VALUES
	('Primeira Geração I', '1996-02-27', 151),
    ('Segunda Geração II', '1999-11-21', 100),
    ('Terceira Geração III', '2002-11-21', 135),
    ('Quarta Geração IV', '2006-09-28', 107),
    ('Quinta Geração V', '2010-09-18', 156),
    ('Sexta Geração VI', '2013-10-12', 72),
    ('Sétima Geração VII', '2016-11-18', 88),
    ('Oitava Geração VIII', '2019-11-15', 96),
    ('Nona Geração IX', '2022-11-18', 120);
    
SELECT * FROM geracoes;
    
INSERT INTO jogos (nome, lancamento, id_geracao) VALUES
	-- Gen 1
	('Pokémon Red', '1996-02-27', 1),
	('Pokémon Green', '1996-02-27', 1),
	('Pokémon Blue (JP)', '1996-10-15', 1),
	('Pokémon Yellow', '1998-09-12', 1),
	-- Gen 2
	('Pokémon Gold', '1999-11-21', 2),
	('Pokémon Silver', '1999-11-21', 2),
	('Pokémon Crystal', '2000-12-14', 2),
	-- Gen 3
	('Pokémon Ruby', '2002-11-21', 3),
	('Pokémon Sapphire', '2002-11-21', 3),
	('Pokémon FireRed', '2004-01-29', 3),
	('Pokémon LeafGreen', '2004-01-29', 3),
	('Pokémon Emerald', '2004-09-16', 3),
	-- Gen 4
	('Pokémon Diamond', '2006-09-28', 4),
	('Pokémon Pearl', '2006-09-28', 4),
	('Pokémon Platinum', '2008-09-13', 4),
	('Pokémon HeartGold', '2009-09-12', 4),
	('Pokémon SoulSilver', '2009-09-12', 4),
	-- Gen 5
	('Pokémon Black', '2010-09-18', 5),
	('Pokémon White', '2010-09-18', 5),
	('Pokémon Black 2', '2012-06-23', 5),
	('Pokémon White 2', '2012-06-23', 5),
	-- Gen 6
	('Pokémon X', '2013-10-12', 6),
	('Pokémon Y', '2013-10-12', 6),
	('Pokémon Omega Ruby', '2014-11-21', 6),
	('Pokémon Alpha Sapphire', '2014-11-21', 6),
	-- Gen 7
	('Pokémon Sun', '2016-11-18', 7),
	('Pokémon Moon', '2016-11-18', 7),
	('Pokémon Ultra Sun', '2017-11-17', 7),
	('Pokémon Ultra Moon', '2017-11-17', 7),
	('Pokémon Let''s Go Pikachu', '2018-11-16', 7),
	('Pokémon Let''s Go Eevee', '2018-11-16', 7),
	-- Gen 8
	('Pokémon Sword', '2019-11-15', 8),
	('Pokémon Shield', '2019-11-15', 8),
	('Pokémon Brilliant Diamond', '2021-11-19', 8),
	('Pokémon Shining Pearl', '2021-11-19', 8),
	('Pokémon Legends Arceus', '2022-01-28', 8),
	-- Gen 9
	('Pokémon Scarlet', '2022-11-18', 9),
	('Pokémon Violet', '2022-11-18', 9);
    
-- Primeira geração de pokemon
INSERT INTO pokemon (nome, tipagem_1, tipagem_2, foto_url, cor_principal, cor_secundaria, id_geracao) VALUES
	('Bulbasaur','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/bulbasaur.avif','#78C850','#4E8234',1),
	('Ivysaur','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/ivysaur.avif','#5FAF5A','#2E6B3A',1),
	('Venusaur','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/venusaur.avif','#2E8B57','#1F4D36',1),
	('Charmander','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/charmander.avif','#F08030','#C75B12',1),
	('Charmeleon','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/charmeleon.avif','#D94A2B','#7A1F12',1),
	('Charizard','Fogo','Voador','https://img.pokemondb.net/artwork/avif/charizard.avif','#F08030','#2B2B2B',1),
	('Squirtle','Água',NULL,'https://img.pokemondb.net/artwork/avif/squirtle.avif','#6890F0','#2F5FA5',1),
	('Wartortle','Água',NULL,'https://img.pokemondb.net/artwork/avif/wartortle.avif','#4A7BD1','#1E3A70',1),
	('Blastoise','Água',NULL,'https://img.pokemondb.net/artwork/avif/blastoise.avif','#3A6FCF','#1C2F6B',1),
	('Caterpie','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/caterpie.avif','#7AC74C','#2E6B1F',1),
	('Metapod','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/metapod.avif','#6AA84F','#3D5F2A',1),
	('Butterfree','Inseto','Voador','https://img.pokemondb.net/artwork/avif/butterfree.avif','#C6B7E2','#6A5A8B',1),
	('Weedle','Inseto','Venenoso','https://img.pokemondb.net/artwork/avif/weedle.avif','#C2A23A','#5A3B00',1),
	('Kakuna','Inseto','Venenoso','https://img.pokemondb.net/artwork/avif/kakuna.avif','#B89A2F','#4F3A00',1),
	('Beedrill','Inseto','Venenoso','https://img.pokemondb.net/artwork/avif/beedrill.avif','#D4A017','#2B2B2B',1),
	('Pidgey','Normal','Voador','https://img.pokemondb.net/artwork/avif/pidgey.avif','#C6A26B','#6B4F2E',1),
	('Pidgeotto','Normal','Voador','https://img.pokemondb.net/artwork/avif/pidgeotto.avif','#B88A4A','#5A3A1F',1),
	('Pidgeot','Normal','Voador','https://img.pokemondb.net/artwork/avif/pidgeot.avif','#D89C4A','#5A2E1F',1),
	('Rattata','Normal',NULL,'https://img.pokemondb.net/artwork/avif/rattata.avif','#8A5A8A','#3B1F3B',1),
	('Raticate','Normal',NULL,'https://img.pokemondb.net/artwork/avif/raticate.avif','#A05A2C','#4A2A12',1),
	('Spearow','Normal','Voador','https://img.pokemondb.net/artwork/avif/spearow.avif','#8A4B2D','#3A1F12',1),
	('Fearow','Normal','Voador','https://img.pokemondb.net/artwork/avif/fearow.avif','#A86B3A','#4A2F1A',1),
	('Ekans','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/ekans.avif','#6A3D9A','#2E1A4F',1),
	('Arbok','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/arbok.avif','#7B3FA0','#2E1A4F',1),
	('Pikachu','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/pikachu.avif','#FFD700','#B8860B',1),
	('Raichu','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/raichu.avif','#E69500','#7A3E00',1),
	('Sandshrew','Terra',NULL,'https://img.pokemondb.net/artwork/avif/sandshrew.avif','#D2B48C','#8B7355',1),
	('Sandslash','Terra',NULL,'https://img.pokemondb.net/artwork/avif/sandslash.avif','#C2A06B','#6B4F2E',1),
	('Nidoran♀','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/nidoran-f.avif','#9B59B6','#4A235A',1),
	('Nidorina','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/nidorina.avif','#A569BD','#4A235A',1),
	('Nidoqueen','Venenoso','Terra','https://img.pokemondb.net/artwork/avif/nidoqueen.avif','#5DADE2','#1B4F72',1),
	('Nidoran♂','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/nidoran-m.avif','#5DADE2','#1B4F72',1),
	('Nidorino','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/nidorino.avif','#6C5CE7','#2C2C54',1),
	('Nidoking','Venenoso','Terra','https://img.pokemondb.net/artwork/avif/nidoking.avif','#6A5A8B','#2E2E33',1),
	('Clefairy','Fada',NULL,'https://img.pokemondb.net/artwork/avif/clefairy.avif','#F5B7B1','#C39BD3',1),
	('Clefable','Fada',NULL,'https://img.pokemondb.net/artwork/avif/clefable.avif','#F8C8DC','#D2B4DE',1),
	('Vulpix','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/vulpix.avif','#E67E22','#6E2C00',1),
	('Ninetales','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/ninetales.avif','#FDEBD0','#E67E22',1),
	('Jigglypuff','Normal','Fada','https://img.pokemondb.net/artwork/avif/jigglypuff.avif','#F8C8DC','#2E2E2E',1),
	('Wigglytuff','Normal','Fada','https://img.pokemondb.net/artwork/avif/wigglytuff.avif','#F5B7B1','#8E44AD',1),
	('Zubat','Venenoso','Voador','https://img.pokemondb.net/artwork/avif/zubat.avif','#2C3E50','#5DADE2',1),
	('Golbat','Venenoso','Voador','https://img.pokemondb.net/artwork/avif/golbat.avif','#5B2C6F','#85C1E9',1),
	('Oddish','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/oddish.avif','#2ECC71','#1B4F72',1),
	('Gloom','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/gloom.avif','#5B2C6F','#85C1E9',1),
	('Vileplume','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/vileplume.avif','#C0392B','#F1C40F',1),
	('Paras','Inseto','Planta','https://img.pokemondb.net/artwork/avif/paras.avif','#E74C3C','#F1C40F',1),
	('Parasect','Inseto','Planta','https://img.pokemondb.net/artwork/avif/parasect.avif','#C0392B','#7D6608',1),
	('Venonat','Inseto','Venenoso','https://img.pokemondb.net/artwork/avif/venonat.avif','#8E44AD','#5DADE2',1),
	('Venomoth','Inseto','Venenoso','https://img.pokemondb.net/artwork/avif/venomoth.avif','#AF7AC5','#F8C8DC',1),
	('Diglett','Terra',NULL,'https://img.pokemondb.net/artwork/avif/diglett.avif','#A04000','#F5CBA7',1),
	('Dugtrio','Terra',NULL,'https://img.pokemondb.net/artwork/avif/dugtrio.avif','#8B4513','#F5CBA7',1),
	('Meowth','Normal',NULL,'https://img.pokemondb.net/artwork/avif/meowth.avif','#F8E5A3','#B7950B',1),
	('Persian','Normal',NULL,'https://img.pokemondb.net/artwork/avif/persian.avif','#F5CBA7','#7B241C',1),
	('Psyduck','Água',NULL,'https://img.pokemondb.net/artwork/avif/psyduck.avif','#F4D03F','#2E86C1',1),
	('Golduck','Água',NULL,'https://img.pokemondb.net/artwork/avif/golduck.avif','#2E86C1','#F4D03F',1),
	('Mankey','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/mankey.avif','#D7CCC8','#4E342E',1),
	('Primeape','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/primeape.avif','#F5F5F5','#3E2723',1),
	('Growlithe','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/growlithe.avif','#E67E22','#FDEBD0',1),
	('Arcanine','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/arcanine.avif','#D35400','#FDEBD0',1),
	('Poliwag','Água',NULL,'https://img.pokemondb.net/artwork/avif/poliwag.avif','#5DADE2','#2C3E50',1),
	('Poliwhirl','Água',NULL,'https://img.pokemondb.net/artwork/avif/poliwhirl.avif','#5DADE2','#2C3E50',1),
	('Poliwrath','Água','Lutador','https://img.pokemondb.net/artwork/avif/poliwrath.avif','#2E86C1','#F8F9F9',1),
	('Abra','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/abra.avif','#F4D03F','#6C3483',1),
	('Kadabra','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/kadabra.avif','#F1C40F','#5B2C6F',1),
	('Alakazam','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/alakazam.avif','#F39C12','#4A235A',1),
	('Machop','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/machop.avif','#7FB3D5','#2C3E50',1),
	('Machoke','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/machoke.avif','#5DADE2','#1B2631',1),
	('Machamp','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/machamp.avif','#2E86C1','#17202A',1),
	('Bellsprout','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/bellsprout.avif','#7DCEA0','#1E8449',1),
	('Weepinbell','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/weepinbell.avif','#F4D03F','#1E8449',1),
	('Victreebel','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/victreebel.avif','#D4AC0D','#145A32',1),
	('Tentacool','Água','Venenoso','https://img.pokemondb.net/artwork/avif/tentacool.avif','#85C1E9','#AF7AC5',1),
	('Tentacruel','Água','Venenoso','https://img.pokemondb.net/artwork/avif/tentacruel.avif','#5DADE2','#8E44AD',1),
	('Geodude','Pedra','Terra','https://img.pokemondb.net/artwork/avif/geodude.avif','#7B7D7D','#2E2E2E',1),
	('Graveler','Pedra','Terra','https://img.pokemondb.net/artwork/avif/graveler.avif','#626567','#1C1C1C',1),
	('Golem','Pedra','Terra','https://img.pokemondb.net/artwork/avif/golem.avif','#5D6D7E','#2C3E50',1),
	('Ponyta','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/ponyta.avif','#F5CBA7','#E74C3C',1),
	('Rapidash','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/rapidash.avif','#FDEBD0','#E74C3C',1),
	('Slowpoke','Água','Psíquico','https://img.pokemondb.net/artwork/avif/slowpoke.avif','#F5B7B1','#7D3C98',1),
	('Slowbro','Água','Psíquico','https://img.pokemondb.net/artwork/avif/slowbro.avif','#F1948A','#6C3483',1),
	('Magnemite','Elétrico','Aço','https://img.pokemondb.net/artwork/avif/magnemite.avif','#D5D8DC','#5D6D7E',1),
	('Magneton','Elétrico','Aço','https://img.pokemondb.net/artwork/avif/magneton.avif','#BDC3C7','#2C3E50',1),
	('Farfetch''d','Normal','Voador','https://img.pokemondb.net/artwork/avif/farfetchd.avif','#F0E68C','#2E8B57',1),
	('Doduo','Normal','Voador','https://img.pokemondb.net/artwork/avif/doduo.avif','#A04000','#F5CBA7',1),
	('Dodrio','Normal','Voador','https://img.pokemondb.net/artwork/avif/dodrio.avif','#8B4513','#F8C471',1),
	('Seel','Água',NULL,'https://img.pokemondb.net/artwork/avif/seel.avif','#ECF0F1','#5DADE2',1),
	('Dewgong','Água','Gelo','https://img.pokemondb.net/artwork/avif/dewgong.avif','#D6EAF8','#5DADE2',1),
	('Grimer','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/grimer.avif','#7D3C98','#2E2E2E',1),
	('Muk','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/muk.avif','#6C3483','#1C1C1C',1),
	('Shellder','Água',NULL,'https://img.pokemondb.net/artwork/avif/shellder.avif','#AF7AC5','#2E86C1',1),
	('Cloyster','Água','Gelo','https://img.pokemondb.net/artwork/avif/cloyster.avif','#8E44AD','#5DADE2',1),
	('Gastly','Fantasma','Venenoso','https://img.pokemondb.net/artwork/avif/gastly.avif','#2C2C54','#8E44AD',1),
	('Haunter','Fantasma','Venenoso','https://img.pokemondb.net/artwork/avif/haunter.avif','#4A235A','#AF7AC5',1),
	('Gengar','Fantasma','Venenoso','https://img.pokemondb.net/artwork/avif/gengar.avif','#5B2C6F','#2C2C54',1),
	('Onix','Pedra','Terra','https://img.pokemondb.net/artwork/avif/onix.avif','#566573','#1C2833',1),
	('Drowzee','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/drowzee.avif','#F4D03F','#6C3483',1),
	('Hypno','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/hypno.avif','#F1C40F','#4A235A',1),
	('Krabby','Água',NULL,'https://img.pokemondb.net/artwork/avif/krabby.avif','#E74C3C','#2E86C1',1),
	('Kingler','Água',NULL,'https://img.pokemondb.net/artwork/avif/kingler.avif','#C0392B','#5DADE2',1),
	('Voltorb','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/voltorb.avif','#E74C3C','#ECF0F1',1),
	('Electrode','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/electrode.avif','#ECF0F1','#E74C3C',1),
	('Exeggcute','Planta','Psíquico','https://img.pokemondb.net/artwork/avif/exeggcute.avif','#F5CBA7','#6C3483',1),
	('Exeggutor','Planta','Psíquico','https://img.pokemondb.net/artwork/avif/exeggutor.avif','#A9DFBF','#7B241C',1),
	('Cubone','Terra',NULL,'https://img.pokemondb.net/artwork/avif/cubone.avif','#F5CBA7','#5D4037',1),
	('Marowak','Terra',NULL,'https://img.pokemondb.net/artwork/avif/marowak.avif','#D7CCC8','#3E2723',1),
	('Hitmonlee','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/hitmonlee.avif','#A04000','#2E2E2E',1),
	('Hitmonchan','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/hitmonchan.avif','#8E44AD','#2E2E2E',1),
	('Lickitung','Normal',NULL,'https://img.pokemondb.net/artwork/avif/lickitung.avif','#F5B7B1','#8E44AD',1),
	('Koffing','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/koffing.avif','#AF7AC5','#2E2E2E',1),
	('Weezing','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/weezing.avif','#A569BD','#1C1C1C',1),
	('Rhyhorn','Terra','Pedra','https://img.pokemondb.net/artwork/avif/rhyhorn.avif','#7B7D7D','#2E2E2E',1),
	('Rhydon','Terra','Pedra','https://img.pokemondb.net/artwork/avif/rhydon.avif','#626567','#1C1C1C',1),
	('Chansey','Normal',NULL,'https://img.pokemondb.net/artwork/avif/chansey.avif','#FADBD8','#EC7063',1),
	('Tangela','Planta',NULL,'https://img.pokemondb.net/artwork/avif/tangela.avif','#2E86C1','#1B4F72',1),
	('Kangaskhan','Normal',NULL,'https://img.pokemondb.net/artwork/avif/kangaskhan.avif','#A1887F','#4E342E',1),
	('Horsea','Água',NULL,'https://img.pokemondb.net/artwork/avif/horsea.avif','#5DADE2','#1B4F72',1),
	('Seadra','Água',NULL,'https://img.pokemondb.net/artwork/avif/seadra.avif','#2E86C1','#154360',1),
	('Goldeen','Água',NULL,'https://img.pokemondb.net/artwork/avif/goldeen.avif','#F4D03F','#E74C3C',1),
	('Seaking','Água',NULL,'https://img.pokemondb.net/artwork/avif/seaking.avif','#F39C12','#C0392B',1),
	('Staryu','Água',NULL,'https://img.pokemondb.net/artwork/avif/staryu.avif','#F5B041','#8E44AD',1),
	('Starmie','Água','Psíquico','https://img.pokemondb.net/artwork/avif/starmie.avif','#9B59B6','#F1C40F',1),
	('Mr. Mime','Psíquico','Fada','https://img.pokemondb.net/artwork/avif/mr-mime.avif','#F5B7B1','#5DADE2',1),
	('Scyther','Inseto','Voador','https://img.pokemondb.net/artwork/avif/scyther.avif','#58D68D','#1E8449',1),
	('Jynx','Gelo','Psíquico','https://img.pokemondb.net/artwork/avif/jynx.avif','#8E44AD','#F5CBA7',1),
	('Electabuzz','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/electabuzz.avif','#F4D03F','#2E2E2E',1),
	('Magmar','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/magmar.avif','#E74C3C','#F39C12',1),
	('Pinsir','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/pinsir.avif','#8B4513','#2E2E2E',1),
	('Tauros','Normal',NULL,'https://img.pokemondb.net/artwork/avif/tauros.avif','#5D4037','#1C1C1C',1),
	('Magikarp','Água',NULL,'https://img.pokemondb.net/artwork/avif/magikarp.avif','#E74C3C','#F5CBA7',1),
	('Gyarados','Água','Voador','https://img.pokemondb.net/artwork/avif/gyarados.avif','#2E86C1','#154360',1),
	('Lapras','Água','Gelo','https://img.pokemondb.net/artwork/avif/lapras.avif','#5DADE2','#2C3E50',1),
	('Ditto','Normal',NULL,'https://img.pokemondb.net/artwork/avif/ditto.avif','#AF7AC5','#5B2C6F',1),
	('Eevee','Normal',NULL,'https://img.pokemondb.net/artwork/avif/eevee.avif','#A0522D','#3E2723',1),
	('Vaporeon','Água',NULL,'https://img.pokemondb.net/artwork/avif/vaporeon.avif','#3498DB','#1B4F72',1),
	('Jolteon','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/jolteon.avif','#F4D03F','#B7950B',1),
	('Flareon','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/flareon.avif','#E67E22','#922B21',1),
	('Porygon','Normal',NULL,'https://img.pokemondb.net/artwork/avif/porygon.avif','#F5B7B1','#5DADE2',1),
	('Omanyte','Pedra','Água','https://img.pokemondb.net/artwork/avif/omanyte.avif','#5DADE2','#2E2E2E',1),
	('Omastar','Pedra','Água','https://img.pokemondb.net/artwork/avif/omastar.avif','#2E86C1','#1C1C1C',1),
	('Kabuto','Pedra','Água','https://img.pokemondb.net/artwork/avif/kabuto.avif','#A04000','#2E2E2E',1),
	('Kabutops','Pedra','Água','https://img.pokemondb.net/artwork/avif/kabutops.avif','#8B4513','#1C1C1C',1),
	('Aerodactyl','Pedra','Voador','https://img.pokemondb.net/artwork/avif/aerodactyl.avif','#7F8C8D','#2C3E50',1),
	('Snorlax','Normal',NULL,'https://img.pokemondb.net/artwork/avif/snorlax.avif','#2C3E50','#F5CBA7',1),
	('Articuno','Gelo','Voador','https://img.pokemondb.net/artwork/avif/articuno.avif','#AED6F1','#5DADE2',1),
	('Zapdos','Elétrico','Voador','https://img.pokemondb.net/artwork/avif/zapdos.avif','#F1C40F','#2E2E2E',1),
	('Moltres','Fogo','Voador','https://img.pokemondb.net/artwork/avif/moltres.avif','#E74C3C','#F39C12',1),
	('Dratini','Dragão',NULL,'https://img.pokemondb.net/artwork/avif/dratini.avif','#85C1E9','#2E86C1',1),
	('Dragonair','Dragão',NULL,'https://img.pokemondb.net/artwork/avif/dragonair.avif','#AED6F1','#5DADE2',1),
	('Dragonite','Dragão','Voador','https://img.pokemondb.net/artwork/avif/dragonite.avif','#F5B041','#8E44AD',1),
	('Mewtwo','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/mewtwo.avif','#D7BDE2','#6C3483',1),
	('Mew','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/mew.avif','#FADBD8','#F1948A',1);
    
-- Segunda geração
INSERT INTO pokemon (nome, tipagem_1, tipagem_2, foto_url, cor_principal, cor_secundaria, id_geracao) VALUES
	('Chikorita','Planta',NULL,'https://img.pokemondb.net/artwork/avif/chikorita.avif','#7AC74C','#2E6B1F',2),
	('Bayleef','Planta',NULL,'https://img.pokemondb.net/artwork/avif/bayleef.avif','#66BB6A','#1B5E20',2),
	('Meganium','Planta',NULL,'https://img.pokemondb.net/artwork/avif/meganium.avif','#58D68D','#145A32',2),
	('Cyndaquil','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/cyndaquil.avif','#F5CBA7','#E67E22',2),
	('Quilava','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/quilava.avif','#E67E22','#922B21',2),
	('Typhlosion','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/typhlosion.avif','#2E2E2E','#E74C3C',2),
	('Totodile','Água',NULL,'https://img.pokemondb.net/artwork/avif/totodile.avif','#5DADE2','#1B4F72',2),
	('Croconaw','Água',NULL,'https://img.pokemondb.net/artwork/avif/croconaw.avif','#2E86C1','#154360',2),
	('Feraligatr','Água',NULL,'https://img.pokemondb.net/artwork/avif/feraligatr.avif','#1F618D','#0B3C5D',2),
	('Sentret','Normal',NULL,'https://img.pokemondb.net/artwork/avif/sentret.avif','#D7CCC8','#4E342E',2),
	('Furret','Normal',NULL,'https://img.pokemondb.net/artwork/avif/furret.avif','#F5CBA7','#6E2C00',2),
	('Hoothoot','Normal','Voador','https://img.pokemondb.net/artwork/avif/hoothoot.avif','#8D6E63','#3E2723',2),
	('Noctowl','Normal','Voador','https://img.pokemondb.net/artwork/avif/noctowl.avif','#A1887F','#2C3E50',2),
	('Ledyba','Inseto','Voador','https://img.pokemondb.net/artwork/avif/ledyba.avif','#E74C3C','#2C3E50',2),
	('Ledian','Inseto','Voador','https://img.pokemondb.net/artwork/avif/ledian.avif','#C0392B','#1C1C1C',2),
	('Spinarak','Inseto','Venenoso','https://img.pokemondb.net/artwork/avif/spinarak.avif','#27AE60','#6C3483',2),
	('Ariados','Inseto','Venenoso','https://img.pokemondb.net/artwork/avif/ariados.avif','#C0392B','#6C3483',2),
	('Crobat','Venenoso','Voador','https://img.pokemondb.net/artwork/avif/crobat.avif','#5B2C6F','#1C1C1C',2),
	('Chinchou','Água','Elétrico','https://img.pokemondb.net/artwork/avif/chinchou.avif','#5DADE2','#F4D03F',2),
	('Lanturn','Água','Elétrico','https://img.pokemondb.net/artwork/avif/lanturn.avif','#2E86C1','#F1C40F',2),
	('Pichu','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/pichu.avif','#F4D03F','#6E2C00',2),
	('Cleffa','Fada',NULL,'https://img.pokemondb.net/artwork/avif/cleffa.avif','#FADBD8','#D2B4DE',2),
	('Igglybuff','Normal','Fada','https://img.pokemondb.net/artwork/avif/igglybuff.avif','#F5B7B1','#8E44AD',2),
	('Togepi','Fada',NULL,'https://img.pokemondb.net/artwork/avif/togepi.avif','#FDEBD0','#F1C40F',2),
	('Togetic','Fada','Voador','https://img.pokemondb.net/artwork/avif/togetic.avif','#F8F9F9','#5DADE2',2),
	('Natu','Psíquico','Voador','https://img.pokemondb.net/artwork/avif/natu.avif','#27AE60','#E74C3C',2),
	('Xatu','Psíquico','Voador','https://img.pokemondb.net/artwork/avif/xatu.avif','#1E8449','#C0392B',2),
	('Mareep','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/mareep.avif','#F8E287','#C7A600',2),
	('Flaaffy','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/flaaffy.avif','#F5B7B1','#F4D03F',2),
	('Ampharos','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/ampharos.avif','#F4D03F','#922B21',2),
	('Bellossom','Planta',NULL,'https://img.pokemondb.net/artwork/avif/bellossom.avif','#27AE60','#F1C40F',2),
	('Marill','Água','Fada','https://img.pokemondb.net/artwork/avif/marill.avif','#5DADE2','#ECF0F1',2),
	('Azumarill','Água','Fada','https://img.pokemondb.net/artwork/avif/azumarill.avif','#3498DB','#F8F9F9',2),
	('Sudowoodo','Pedra',NULL,'https://img.pokemondb.net/artwork/avif/sudowoodo.avif','#8B4513','#27AE60',2),
	('Politoed','Água',NULL,'https://img.pokemondb.net/artwork/avif/politoed.avif','#7DCEA0','#F1C40F',2),
	('Hoppip','Planta','Voador','https://img.pokemondb.net/artwork/avif/hoppip.avif','#F5B7B1','#7DCEA0',2),
	('Skiploom','Planta','Voador','https://img.pokemondb.net/artwork/avif/skiploom.avif','#58D68D','#F8C471',2),
	('Jumpluff','Planta','Voador','https://img.pokemondb.net/artwork/avif/jumpluff.avif','#AED6F1','#58D68D',2),
	('Aipom','Normal',NULL,'https://img.pokemondb.net/artwork/avif/aipom.avif','#BB8FCE','#4A235A',2),
	('Sunkern','Planta',NULL,'https://img.pokemondb.net/artwork/avif/sunkern.avif','#F4D03F','#7D6608',2),
	('Sunflora','Planta',NULL,'https://img.pokemondb.net/artwork/avif/sunflora.avif','#F1C40F','#27AE60',2),
	('Yanma','Inseto','Voador','https://img.pokemondb.net/artwork/avif/yanma.avif','#58D68D','#C0392B',2),
	('Wooper','Água','Terra','https://img.pokemondb.net/artwork/avif/wooper.avif','#85C1E9','#5B2C6F',2),
	('Quagsire','Água','Terra','https://img.pokemondb.net/artwork/avif/quagsire.avif','#6A5A8B','#83D5F6',2),
	('Espeon','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/espeon.avif','#C39BD3','#5B2C6F',2),
	('Umbreon','Sombrio',NULL,'https://img.pokemondb.net/artwork/avif/umbreon.avif','#2C3E50','#F4D03F',2),
	('Murkrow','Sombrio','Voador','https://img.pokemondb.net/artwork/avif/murkrow.avif','#1C1C1C','#5B2C6F',2),
	('Slowking','Água','Psíquico','https://img.pokemondb.net/artwork/avif/slowking.avif','#F1948A','#6C3483',2),
	('Misdreavus','Fantasma',NULL,'https://img.pokemondb.net/artwork/avif/misdreavus.avif','#8E44AD','#1C1C1C',2),
	('Unown','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/unown.avif','#2C3E50','#1C1C1C',2),
	('Wobbuffet','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/wobbuffet.avif','#5DADE2','#2C3E50',2),
	('Girafarig','Normal','Psíquico','https://img.pokemondb.net/artwork/avif/girafarig.avif','#F4D03F','#8E44AD',2),
	('Pineco','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/pineco.avif','#A04000','#1C1C1C',2),
	('Forretress','Inseto','Aço','https://img.pokemondb.net/artwork/avif/forretress.avif','#AF7AC5','#2C3E50',2),
	('Dunsparce','Normal',NULL,'https://img.pokemondb.net/artwork/avif/dunsparce.avif','#F8E287','#85C1E9',2),
	('Gligar','Terra','Voador','https://img.pokemondb.net/artwork/avif/gligar.avif','#BB8FCE','#2E2E2E',2),
	('Steelix','Aço','Terra','https://img.pokemondb.net/artwork/avif/steelix.avif','#5D6D7E','#1C1C1C',2),
	('Snubbull','Fada',NULL,'https://img.pokemondb.net/artwork/avif/snubbull.avif','#F1948A','#7B241C',2),
	('Granbull','Fada',NULL,'https://img.pokemondb.net/artwork/avif/granbull.avif','#EC7063','#4A235A',2),
	('Qwilfish','Água','Venenoso','https://img.pokemondb.net/artwork/avif/qwilfish.avif','#AF7AC5','#5DADE2',2),
	('Scizor','Inseto','Aço','https://img.pokemondb.net/artwork/avif/scizor.avif','#C0392B','#1C1C1C',2),
	('Shuckle','Inseto','Pedra','https://img.pokemondb.net/artwork/avif/shuckle.avif','#F4D03F','#C0392B',2),
	('Heracross','Inseto','Lutador','https://img.pokemondb.net/artwork/avif/heracross.avif','#2E86C1','#1C1C1C',2),
	('Sneasel','Sombrio','Gelo','https://img.pokemondb.net/artwork/avif/sneasel.avif','#5DADE2','#8E44AD',2),
	('Teddiursa','Normal',NULL,'https://img.pokemondb.net/artwork/avif/teddiursa.avif','#A0522D','#F5CBA7',2),
	('Ursaring','Normal',NULL,'https://img.pokemondb.net/artwork/avif/ursaring.avif','#8B4513','#F5CBA7',2),
	('Slugma','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/slugma.avif','#E74C3C','#F39C12',2),
	('Magcargo','Fogo','Pedra','https://img.pokemondb.net/artwork/avif/magcargo.avif','#C0392B','#7B241C',2),
	('Swinub','Gelo','Terra','https://img.pokemondb.net/artwork/avif/swinub.avif','#D7CCC8','#5D4037',2),
	('Piloswine','Gelo','Terra','https://img.pokemondb.net/artwork/avif/piloswine.avif','#A1887F','#3E2723',2),
	('Corsola','Água','Pedra','https://img.pokemondb.net/artwork/avif/corsola.avif','#F5B7B1','#5DADE2',2),
	('Remoraid','Água',NULL,'https://img.pokemondb.net/artwork/avif/remoraid.avif','#E74C3C','#ECF0F1',2),
	('Octillery','Água',NULL,'https://img.pokemondb.net/artwork/avif/octillery.avif','#C0392B','#F5CBA7',2),
	('Delibird','Gelo','Voador','https://img.pokemondb.net/artwork/avif/delibird.avif','#ECF0F1','#E74C3C',2),
	('Mantine','Água','Voador','https://img.pokemondb.net/artwork/avif/mantine.avif','#2E86C1','#1C1C1C',2),
	('Skarmory','Aço','Voador','https://img.pokemondb.net/artwork/avif/skarmory.avif','#BDC3C7','#2C3E50',2),
	('Houndour','Sombrio','Fogo','https://img.pokemondb.net/artwork/avif/houndour.avif','#1C1C1C','#E74C3C',2),
	('Houndoom','Sombrio','Fogo','https://img.pokemondb.net/artwork/avif/houndoom.avif','#2E2E2E','#C0392B',2),
	('Kingdra','Água','Dragão','https://img.pokemondb.net/artwork/avif/kingdra.avif','#2E86C1','#8E44AD',2),
	('Phanpy','Terra',NULL,'https://img.pokemondb.net/artwork/avif/phanpy.avif','#85C1E9','#5D6D7E',2),
	('Donphan','Terra',NULL,'https://img.pokemondb.net/artwork/avif/donphan.avif','#5D6D7E','#1C1C1C',2),
	('Porygon2','Normal',NULL,'https://img.pokemondb.net/artwork/avif/porygon2.avif','#F5B7B1','#5DADE2',2),
	('Stantler','Normal',NULL,'https://img.pokemondb.net/artwork/avif/stantler.avif','#A0522D','#F5CBA7',2),
	('Smeargle','Normal',NULL,'https://img.pokemondb.net/artwork/avif/smeargle.avif','#F8F9F9','#27AE60',2),
	('Tyrogue','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/tyrogue.avif','#BB8FCE','#2C3E50',2),
	('Hitmontop','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/hitmontop.avif','#8E44AD','#2E2E2E',2),
	('Smoochum','Gelo','Psíquico','https://img.pokemondb.net/artwork/avif/smoochum.avif','#F5CBA7','#8E44AD',2),
	('Elekid','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/elekid.avif','#F4D03F','#2E2E2E',2),
	('Magby','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/magby.avif','#E74C3C','#F39C12',2),
	('Miltank','Normal',NULL,'https://img.pokemondb.net/artwork/avif/miltank.avif','#FADBD8','#5D6D7E',2),
	('Blissey','Normal',NULL,'https://img.pokemondb.net/artwork/avif/blissey.avif','#FDEDEC','#F1948A',2),
	('Raikou','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/raikou.avif','#F4D03F','#5D6D7E',2),
	('Entei','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/entei.avif','#A93226','#F5CBA7',2),
	('Suicune','Água',NULL,'https://img.pokemondb.net/artwork/avif/suicune.avif','#5DADE2','#8E44AD',2),
	('Larvitar','Pedra','Terra','https://img.pokemondb.net/artwork/avif/larvitar.avif','#58D68D','#2E2E2E',2),
	('Pupitar','Pedra','Terra','https://img.pokemondb.net/artwork/avif/pupitar.avif','#7F8C8D','#1C1C1C',2),
	('Tyranitar','Pedra','Sombrio','https://img.pokemondb.net/artwork/avif/tyranitar.avif','#1E8449','#2E2E2E',2),
	('Lugia','Psíquico','Voador','https://img.pokemondb.net/artwork/avif/lugia.avif','#ECF0F1','#5DADE2',2),
	('Ho-Oh','Fogo','Voador','https://img.pokemondb.net/artwork/avif/ho-oh.avif','#E74C3C','#F1C40F',2),
	('Celebi','Psíquico','Planta','https://img.pokemondb.net/artwork/avif/celebi.avif','#58D68D','#8E44AD',2);

-- Terceira geração
INSERT INTO pokemon (nome, tipagem_1, tipagem_2, foto_url, cor_principal, cor_secundaria, id_geracao) VALUES
	('Treecko','Planta',NULL,'https://img.pokemondb.net/artwork/avif/treecko.avif','#27AE60','#145A32',3),
	('Grovyle','Planta',NULL,'https://img.pokemondb.net/artwork/avif/grovyle.avif','#1E8449','#0B5345',3),
	('Sceptile','Planta',NULL,'https://img.pokemondb.net/artwork/avif/sceptile.avif','#196F3D','#0B3C2F',3),
	('Torchic','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/torchic.avif','#F5B041','#C0392B',3),
	('Combusken','Fogo','Lutador','https://img.pokemondb.net/artwork/avif/combusken.avif','#E67E22','#922B21',3),
	('Blaziken','Fogo','Lutador','https://img.pokemondb.net/artwork/avif/blaziken.avif','#C0392B','#F5CBA7',3),
	('Mudkip','Água',NULL,'https://img.pokemondb.net/artwork/avif/mudkip.avif','#5DADE2','#1B4F72',3),
	('Marshtomp','Água','Terra','https://img.pokemondb.net/artwork/avif/marshtomp.avif','#2E86C1','#8E6E53',3),
	('Swampert','Água','Terra','https://img.pokemondb.net/artwork/avif/swampert.avif','#1F618D','#6E2C00',3),
	('Poochyena','Sombrio',NULL,'https://img.pokemondb.net/artwork/avif/poochyena.avif','#5D6D7E','#1C1C1C',3),
	('Mightyena','Sombrio',NULL,'https://img.pokemondb.net/artwork/avif/mightyena.avif','#2C3E50','#A04000',3),
	('Zigzagoon','Normal',NULL,'https://img.pokemondb.net/artwork/avif/zigzagoon.avif','#D7CCC8','#4E342E',3),
	('Linoone','Normal',NULL,'https://img.pokemondb.net/artwork/avif/linoone.avif','#F5F5F5','#8B4513',3),
	('Wurmple','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/wurmple.avif','#C0392B','#F1C40F',3),
	('Silcoon','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/silcoon.avif','#F8F9F9','#8E44AD',3),
	('Beautifly','Inseto','Voador','https://img.pokemondb.net/artwork/avif/beautifly.avif','#F5B7B1','#2C3E50',3),
	('Cascoon','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/cascoon.avif','#BB8FCE','#4A235A',3),
	('Dustox','Inseto','Venenoso','https://img.pokemondb.net/artwork/avif/dustox.avif','#7D3C98','#F5B7B1',3),
	('Lotad','Água','Planta','https://img.pokemondb.net/artwork/avif/lotad.avif','#5DADE2','#27AE60',3),
	('Lombre','Água','Planta','https://img.pokemondb.net/artwork/avif/lombre.avif','#27AE60','#5DADE2',3),
	('Ludicolo','Água','Planta','https://img.pokemondb.net/artwork/avif/ludicolo.avif','#1E8449','#F4D03F',3),
	('Seedot','Planta',NULL,'https://img.pokemondb.net/artwork/avif/seedot.avif','#8B4513','#1C1C1C',3),
	('Nuzleaf','Planta','Sombrio','https://img.pokemondb.net/artwork/avif/nuzleaf.avif','#7B241C','#145A32',3),
	('Shiftry','Planta','Sombrio','https://img.pokemondb.net/artwork/avif/shiftry.avif','#145A32','#8B0000',3),
	('Taillow','Normal','Voador','https://img.pokemondb.net/artwork/avif/taillow.avif','#2E86C1','#C0392B',3),
	('Swellow','Normal','Voador','https://img.pokemondb.net/artwork/avif/swellow.avif','#1F618D','#C0392B',3),
	('Wingull','Água','Voador','https://img.pokemondb.net/artwork/avif/wingull.avif','#ECF0F1','#2E86C1',3),
	('Pelipper','Água','Voador','https://img.pokemondb.net/artwork/avif/pelipper.avif','#F4D03F','#2E86C1',3),
	('Ralts','Psíquico','Fada','https://img.pokemondb.net/artwork/avif/ralts.avif','#F8F9F9','#58D68D',3),
	('Kirlia','Psíquico','Fada','https://img.pokemondb.net/artwork/avif/kirlia.avif','#F5B7B1','#58D68D',3),
	('Gardevoir','Psíquico','Fada','https://img.pokemondb.net/artwork/avif/gardevoir.avif','#ECF0F1','#1E8449',3),
	('Surskit','Inseto','Água','https://img.pokemondb.net/artwork/avif/surskit.avif','#85C1E9','#2E86C1',3),
	('Masquerain','Inseto','Voador','https://img.pokemondb.net/artwork/avif/masquerain.avif','#5DADE2','#C0392B',3),
	('Shroomish','Planta',NULL,'https://img.pokemondb.net/artwork/avif/shroomish.avif','#7DCEA0','#8B4513',3),
	('Breloom','Planta','Lutador','https://img.pokemondb.net/artwork/avif/breloom.avif','#27AE60','#A04000',3),
	('Slakoth','Normal',NULL,'https://img.pokemondb.net/artwork/avif/slakoth.avif','#D7CCC8','#6E2C00',3),
	('Vigoroth','Normal',NULL,'https://img.pokemondb.net/artwork/avif/vigoroth.avif','#F5F5F5','#C0392B',3),
	('Slaking','Normal',NULL,'https://img.pokemondb.net/artwork/avif/slaking.avif','#A04000','#F5CBA7',3),
	('Nincada','Inseto','Terra','https://img.pokemondb.net/artwork/avif/nincada.avif','#7B7D7D','#F1C40F',3),
	('Ninjask','Inseto','Voador','https://img.pokemondb.net/artwork/avif/ninjask.avif','#F1C40F','#2C3E50',3),
	('Shedinja','Inseto','Fantasma','https://img.pokemondb.net/artwork/avif/shedinja.avif','#F8F9F9','#8B4513',3),
	('Whismur','Normal',NULL,'https://img.pokemondb.net/artwork/avif/whismur.avif','#F5B7B1','#8E44AD',3),
	('Loudred','Normal',NULL,'https://img.pokemondb.net/artwork/avif/loudred.avif','#8E44AD','#2C3E50',3),
	('Exploud','Normal',NULL,'https://img.pokemondb.net/artwork/avif/exploud.avif','#5B2C6F','#1C1C1C',3),
    ('Makuhita','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/makuhita.avif','#F4D03F','#2C3E50',3),
	('Hariyama','Lutador',NULL,'https://img.pokemondb.net/artwork/avif/hariyama.avif','#F1C40F','#2E2E2E',3),
	('Azurill','Normal','Fada','https://img.pokemondb.net/artwork/avif/azurill.avif','#85C1E9','#F8F9F9',3),
	('Nosepass','Pedra',NULL,'https://img.pokemondb.net/artwork/avif/nosepass.avif','#5D6D7E','#C0392B',3),
	('Skitty','Normal',NULL,'https://img.pokemondb.net/artwork/avif/skitty.avif','#F5B7B1','#8E44AD',3),
	('Delcatty','Normal',NULL,'https://img.pokemondb.net/artwork/avif/delcatty.avif','#D7BDE2','#5B2C6F',3),
	('Sableye','Sombrio','Fantasma','https://img.pokemondb.net/artwork/avif/sableye.avif','#2C3E50','#5DADE2',3),
	('Mawile','Aço','Fada','https://img.pokemondb.net/artwork/avif/mawile.avif','#F8F9F9','#2C3E50',3),
	('Aron','Aço','Pedra','https://img.pokemondb.net/artwork/avif/aron.avif','#BDC3C7','#2C3E50',3),
	('Lairon','Aço','Pedra','https://img.pokemondb.net/artwork/avif/lairon.avif','#95A5A6','#1C1C1C',3),
	('Aggron','Aço','Pedra','https://img.pokemondb.net/artwork/avif/aggron.avif','#566573','#17202A',3),
	('Meditite','Lutador','Psíquico','https://img.pokemondb.net/artwork/avif/meditite.avif','#5DADE2','#ECF0F1',3),
	('Medicham','Lutador','Psíquico','https://img.pokemondb.net/artwork/avif/medicham.avif','#F5CBA7','#C0392B',3),
	('Electrike','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/electrike.avif','#58D68D','#F4D03F',3),
	('Manectric','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/manectric.avif','#F4D03F','#1C1C1C',3),
	('Plusle','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/plusle.avif','#E74C3C','#F8F9F9',3),
	('Minun','Elétrico',NULL,'https://img.pokemondb.net/artwork/avif/minun.avif','#5DADE2','#F8F9F9',3),
	('Volbeat','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/volbeat.avif','#2C3E50','#F4D03F',3),
	('Illumise','Inseto',NULL,'https://img.pokemondb.net/artwork/avif/illumise.avif','#8E44AD','#F5B7B1',3),
	('Roselia','Planta','Venenoso','https://img.pokemondb.net/artwork/avif/roselia.avif','#27AE60','#C0392B',3),
	('Gulpin','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/gulpin.avif','#58D68D','#1C1C1C',3),
	('Swalot','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/swalot.avif','#7D3C98','#2C3E50',3),
	('Carvanha','Água','Sombrio','https://img.pokemondb.net/artwork/avif/carvanha.avif','#C0392B','#2C3E50',3),
	('Sharpedo','Água','Sombrio','https://img.pokemondb.net/artwork/avif/sharpedo.avif','#2E86C1','#1C1C1C',3),
	('Wailmer','Água',NULL,'https://img.pokemondb.net/artwork/avif/wailmer.avif','#5DADE2','#F8F9F9',3),
	('Wailord','Água',NULL,'https://img.pokemondb.net/artwork/avif/wailord.avif','#2E86C1','#1C1C1C',3),
	('Numel','Fogo','Terra','https://img.pokemondb.net/artwork/avif/numel.avif','#F5CBA7','#A04000',3),
	('Camerupt','Fogo','Terra','https://img.pokemondb.net/artwork/avif/camerupt.avif','#C0392B','#F1C40F',3),
	('Torkoal','Fogo',NULL,'https://img.pokemondb.net/artwork/avif/torkoal.avif','#E67E22','#2E2E2E',3),
	('Spoink','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/spoink.avif','#F5B7B1','#2C3E50',3),
	('Grumpig','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/grumpig.avif','#8E44AD','#F1C40F',3),
	('Spinda','Normal',NULL,'https://img.pokemondb.net/artwork/avif/spinda.avif','#F5CBA7','#C0392B',3),
	('Trapinch','Terra',NULL,'https://img.pokemondb.net/artwork/avif/trapinch.avif','#E67E22','#7D6608',3),
	('Vibrava','Terra','Dragão','https://img.pokemondb.net/artwork/avif/vibrava.avif','#27AE60','#C0392B',3),
	('Flygon','Terra','Dragão','https://img.pokemondb.net/artwork/avif/flygon.avif','#58D68D','#C0392B',3),
	('Cacnea','Planta',NULL,'https://img.pokemondb.net/artwork/avif/cacnea.avif','#27AE60','#7D6608',3),
	('Cacturne','Planta','Sombrio','https://img.pokemondb.net/artwork/avif/cacturne.avif','#145A32','#2C3E50',3),
	('Swablu','Normal','Voador','https://img.pokemondb.net/artwork/avif/swablu.avif','#AED6F1','#ECF0F1',3),
	('Altaria','Dragão','Voador','https://img.pokemondb.net/artwork/avif/altaria.avif','#85C1E9','#F8F9F9',3),
	('Zangoose','Normal',NULL,'https://img.pokemondb.net/artwork/avif/zangoose.avif','#ECF0F1','#C0392B',3),
	('Seviper','Venenoso',NULL,'https://img.pokemondb.net/artwork/avif/seviper.avif','#8E44AD','#F1C40F',3),
	('Lunatone','Pedra','Psíquico','https://img.pokemondb.net/artwork/avif/lunatone.avif','#BDC3C7','#5D6D7E',3),
	('Solrock','Pedra','Psíquico','https://img.pokemondb.net/artwork/avif/solrock.avif','#E67E22','#C0392B',3),
	('Barboach','Água','Terra','https://img.pokemondb.net/artwork/avif/barboach.avif','#85C1E9','#8B4513',3),
	('Whiscash','Água','Terra','https://img.pokemondb.net/artwork/avif/whiscash.avif','#5DADE2','#6E2C00',3),
	('Corphish','Água',NULL,'https://img.pokemondb.net/artwork/avif/corphish.avif','#E74C3C','#F8F9F9',3),
	('Crawdaunt','Água','Sombrio','https://img.pokemondb.net/artwork/avif/crawdaunt.avif','#C0392B','#2C3E50',3),
	('Baltoy','Terra','Psíquico','https://img.pokemondb.net/artwork/avif/baltoy.avif','#D7CCC8','#C0392B',3),
	('Claydol','Terra','Psíquico','https://img.pokemondb.net/artwork/avif/claydol.avif','#A1887F','#7B241C',3),
	('Lileep','Pedra','Planta','https://img.pokemondb.net/artwork/avif/lileep.avif','#58D68D','#8E44AD',3),
	('Cradily','Pedra','Planta','https://img.pokemondb.net/artwork/avif/cradily.avif','#27AE60','#6C3483',3),
	('Anorith','Pedra','Inseto','https://img.pokemondb.net/artwork/avif/anorith.avif','#E67E22','#2C3E50',3),
	('Armaldo','Pedra','Inseto','https://img.pokemondb.net/artwork/avif/armaldo.avif','#A04000','#1C1C1C',3),
	('Feebas','Água',NULL,'https://img.pokemondb.net/artwork/avif/feebas.avif','#D7CCC8','#5DADE2',3),
	('Milotic','Água',NULL,'https://img.pokemondb.net/artwork/avif/milotic.avif','#FDEBD0','#5DADE2',3),
	('Castform','Normal',NULL,'https://img.pokemondb.net/artwork/avif/castform.avif','#F8F9F9','#F1C40F',3),
	('Kecleon','Normal',NULL,'https://img.pokemondb.net/artwork/avif/kecleon.avif','#27AE60','#F5B7B1',3),
	('Shuppet','Fantasma',NULL,'https://img.pokemondb.net/artwork/avif/shuppet.avif','#2C3E50','#8E44AD',3),
	('Banette','Fantasma',NULL,'https://img.pokemondb.net/artwork/avif/banette.avif','#5B2C6F','#F5CBA7',3),
	('Duskull','Fantasma',NULL,'https://img.pokemondb.net/artwork/avif/duskull.avif','#F8F9F9','#2C3E50',3),
	('Dusclops','Fantasma',NULL,'https://img.pokemondb.net/artwork/avif/dusclops.avif','#7D6608','#1C1C1C',3),
	('Tropius','Planta','Voador','https://img.pokemondb.net/artwork/avif/tropius.avif','#58D68D','#F4D03F',3),
	('Chimecho','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/chimecho.avif','#85C1E9','#C0392B',3),
	('Absol','Sombrio',NULL,'https://img.pokemondb.net/artwork/avif/absol.avif','#ECF0F1','#2C3E50',3),
	('Wynaut','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/wynaut.avif','#5DADE2','#2C3E50',3),
	('Snorunt','Gelo',NULL,'https://img.pokemondb.net/artwork/avif/snorunt.avif','#D6EAF8','#E67E22',3),
	('Glalie','Gelo',NULL,'https://img.pokemondb.net/artwork/avif/glalie.avif','#ECF0F1','#2C3E50',3),
	('Spheal','Gelo','Água','https://img.pokemondb.net/artwork/avif/spheal.avif','#85C1E9','#F8F9F9',3),
	('Sealeo','Gelo','Água','https://img.pokemondb.net/artwork/avif/sealeo.avif','#5DADE2','#2C3E50',3),
	('Walrein','Gelo','Água','https://img.pokemondb.net/artwork/avif/walrein.avif','#2E86C1','#1C1C1C',3),
	('Clamperl','Água',NULL,'https://img.pokemondb.net/artwork/avif/clamperl.avif','#FADBD8','#5DADE2',3),
	('Huntail','Água',NULL,'https://img.pokemondb.net/artwork/avif/huntail.avif','#5DADE2','#1C1C1C',3),
	('Gorebyss','Água',NULL,'https://img.pokemondb.net/artwork/avif/gorebyss.avif','#F5B7B1','#85C1E9',3),
	('Relicanth','Água','Pedra','https://img.pokemondb.net/artwork/avif/relicanth.avif','#7B7D7D','#C0392B',3),
	('Luvdisc','Água',NULL,'https://img.pokemondb.net/artwork/avif/luvdisc.avif','#F5B7B1','#5DADE2',3),
	('Bagon','Dragão',NULL,'https://img.pokemondb.net/artwork/avif/bagon.avif','#5DADE2','#2C3E50',3),
	('Shelgon','Dragão',NULL,'https://img.pokemondb.net/artwork/avif/shelgon.avif','#BDC3C7','#2C3E50',3),
	('Salamence','Dragão','Voador','https://img.pokemondb.net/artwork/avif/salamence.avif','#2E86C1','#C0392B',3),
	('Beldum','Aço','Psíquico','https://img.pokemondb.net/artwork/avif/beldum.avif','#BDC3C7','#5DADE2',3),
	('Metang','Aço','Psíquico','https://img.pokemondb.net/artwork/avif/metang.avif','#95A5A6','#2C3E50',3),
	('Metagross','Aço','Psíquico','https://img.pokemondb.net/artwork/avif/metagross.avif','#566573','#1C1C1C',3),
	('Regirock','Pedra',NULL,'https://img.pokemondb.net/artwork/avif/regirock.avif','#A04000','#2E2E2E',3),
	('Regice','Gelo',NULL,'https://img.pokemondb.net/artwork/avif/regice.avif','#D6EAF8','#5DADE2',3),
	('Registeel','Aço',NULL,'https://img.pokemondb.net/artwork/avif/registeel.avif','#BDC3C7','#2C3E50',3),
	('Latias','Dragão','Psíquico','https://img.pokemondb.net/artwork/avif/latias.avif','#E74C3C','#F8F9F9',3),
	('Latios','Dragão','Psíquico','https://img.pokemondb.net/artwork/avif/latios.avif','#2E86C1','#F8F9F9',3),
	('Kyogre','Água',NULL,'https://img.pokemondb.net/artwork/avif/kyogre.avif','#1F618D','#C0392B',3),
	('Groudon','Terra',NULL,'https://img.pokemondb.net/artwork/avif/groudon.avif','#C0392B','#2E2E2E',3),
	('Rayquaza','Dragão','Voador','https://img.pokemondb.net/artwork/avif/rayquaza.avif','#1E8449','#F1C40F',3),
	('Jirachi','Aço','Psíquico','https://img.pokemondb.net/artwork/avif/jirachi.avif','#FDEBD0','#F4D03F',3),
	('Deoxys','Psíquico',NULL,'https://img.pokemondb.net/artwork/avif/deoxys.avif','#E67E22','#5DADE2',3);
    
INSERT INTO usuario (nome, email, senha, admin, id_pokemon_favorito, id_jogo_favorito, id_geracao_favorita) VALUES
	('Quagsire admin', 'admin@email.com', '@Senha242', 1, 195, 10, 1);

SELECT * FROM pokemon;
SELECT COUNT(*) FROM pokemon;

SELECT * FROM pokemon WHERE id_geracao = 1;
SELECT * FROM pokemon WHERE id_geracao = 2;
SELECT * FROM pokemon WHERE id_geracao = 3;
SELECT * FROM pokemon WHERE id_geracao = 4;
SELECT * FROM pokemon WHERE id_geracao = 5;
SELECT * FROM pokemon WHERE id_geracao = 6;
SELECT * FROM pokemon WHERE id_geracao = 7;
SELECT * FROM pokemon WHERE id_geracao = 8;
SELECT * FROM pokemon WHERE id_geracao = 9;

SELECT * FROM usuario;

use pokeverso;

SELECT 
u.nome nome_usuario,
u.email email_usuario,
p.nome pokemon_favorito,
j.nome jogo_favorito,
g.nome geracao_favorito
FROM usuario u
JOIN pokemon p
ON u.id_pokemon_favorito = p.id_pokemon
JOIN jogos j
ON u.id_jogo_favorito = j.id_jogo
JOIN geracoes g
ON u.id_geracao_favorita = g.id_geracao;
